ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLE T_LUTAN_PRODUTOS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME        VARCHAR2(100 BYTE) NOT NULL,
    PRECO       NUMBER NOT NULL,
    QUANTIDADE  NUMBER NOT NULL
);
